config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home_page'
  
  # users
  get '/user_dashboard' => 'users#user_dashboard', as: 'user_dashboard'

  # MainBook
  get '/mainbook' => 'main_books#index'
  get '/mainbook_entries' => 'main_books#mainbook_entries'
  get '/mainbook_entry' => 'main_books#new', as: 'mainbook_new'
  post '/mainbook_entry' => 'main_books#create', as: 'mainbook_entry'
  get '/mainbook/:id/edit' => 'main_books#edit', as: 'edit_mainbook'
  put '/mainbook/:id/edit' => 'main_books#update', as: 'update_mainbook'
  post '/mainbook/:id/delete' => 'main_books#destroy_entry', as: 'delete_entry'

  # export to pdf
  get '/mainbook_export' => 'main_books#export_pdf', as: 'mainbook_export'
  get '/minibook_export' => 'mini_books#export_pdf', as: 'minibook_export'
  get 'mini_books/:mini_book_id/minibook_entries_export' => 'minibook_entries#export_pdf', as: 'minibook_entries_export'

  resources :mini_books do
    resources :minibook_entries
  end

  # Admin
  get 'admins/home' => 'admin_pages#index'
  get 'admins/all_users' => 'admin_pages#all_users'
  get 'admins/paid_users' => 'admin_pages#paid_users'
  get 'admins/free_users' => 'admin_pages#free_users'

  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }, only: [:sessions]

  # user
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations" }, only: [:sessions, :registrations, :confirmations]
 
  
  # scope '/checkout' do
  #   post 'create', to: 'checkout#create', as: 'checkout_create'
  #   get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  #   get 'success', to: 'checkout#success', as: 'checkout_success'
  # end

  #resources :checkout, only: [:create]
  post "checkouts/create", to: "checkouts#create", as: "checkout_create"

  # Products
  get '/products' => 'abc_products#index'
  get '/product/:id/show' => 'abc_products#show', as: 'abc_product_show'
  # get '/product_new' => 'abc_products#new', as: 'abc_product_new'
  # post '/product_new' => 'abc_products#create', as: 'abc_product_create'
  # get '/product/:id/edit' => 'abc_products#edit', as: 'edit_abc_product'
  # put '/product/:id/edit' => 'abc_products#update', as: 'update_abc_product'
  # post '/product/:id/delete' => 'abc_products#destroy', as: 'delete_abc_product'

  get 'pricing', to: 'static_pages#pricing'
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]
end

app/models/mini_book.rb
class MiniBook < ApplicationRecord
  has_many :minibook_entries, dependent: :destroy
  belongs_to :user
  # has_many :checkouts #, dependent: :destroy
  validates :user_id, presence: true
  validates :minibook_name, presence: true
end

app/controllers/mini_books_controller.rb
class MiniBooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: %i[edit update destroy]
  before_action :check_user_status

  def index
    @mini_books = MiniBook.all
  end

  def export_pdf
    @mini_books = MiniBook.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Minibooks as of: #{Time.zone.today}", template: 'mini_books/export_pdf.html.erb'
      end
    end
  end

  def show
    @mini_book = MiniBook.find(params[:id])
  end

  def new
    @mini_book = current_user.mini_books.build
  end

  def create
    @mini_book = current_user.mini_books.build(mini_book_params)
    if @mini_book.save
      redirect_to mini_books_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit
    @mini_book = MiniBook.find(params[:id])
  end

  def update
    @mini_book = MiniBook.find(params[:id])
    if @mini_book.update(mini_book_params)
      flash[:notice] = 'Sucessfully updated MiniBook'
      redirect_to mini_books_path
    else
      render :edit
    end
  end

  def destroy
    @mini_book = MiniBook.find(params[:id])
    if @mini_book.destroy
      flash[:notice] = 'Sucessfully deleted Mini Book'
      redirect_to mini_books_path
    else
      render :mini_books_path
    end
  end

  def correct_user
    @mini_book = current_user.mini_books.find_by(id: params[:id])
    redirect_to mini_books_path, notice: 'Not Authorized to access this page' if @mini_book.nil?
  end

  def check_user_status
    redirect_to products_path, notice: 'Subscribe now to access the page!' if current_user.status == 'free'
  end

  private

  def mini_book_params
    params.require(:mini_book).permit(:user_id, :minibook_name, :minibook_price)
  end
end

app/views/mini_books/_all_minibooks.html.erb
<section class="p-3 my-container">
  <div class="books-table-container">
    <div class="container">
      <div class="card-body", id = "minibook__entry__table">
        <div class="table-responsive">
          <table class="table table-borderless text-white mb-0">
            <thead>
              <tr>
              <td class="label_book_header">Minibook Name</td>
              </tr>
            </thead>
            <tbody>
                <% @mini_books.each do |minibook| %>
                <% if minibook.user == current_user %>
              <tr scope="column">
                <td class="label_book_content_minib"><%= minibook.minibook_name %></td>
                <td>
                  <button type="button" class="btn btn-outline-light", id="table__inside__buttons_minib"><%= link_to 'View Entries', mini_book_minibook_entries_path(mini_book_id: minibook.id) %></button>
                  <button type="button" class="btn btn-outline-light", id="table__inside__buttons_minib"><%= link_to "Edit", edit_mini_book_path(minibook.id) %></button>
                  <button type="button" class="btn btn-outline-light", id="table__inside__buttons_minib"><%= link_to "Delete", mini_book_path(minibook.id), method: :delete, :data => { :confirm => "Are you sure?" } %></button>
                </td>
              </tr>
                <% end %> 
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/mini_books/_minibook_form.html.erb
<%= form_with scope: :mini_book, url: mini_books_path, model: @mini_book, :local => true do |form| %>
    <% if @mini_book.errors.any? %>
    <ul>
      <% @mini_book.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div id = "book__entry__form">
  <h1 id ="mainbook__entry">Create Minibook</h1>
<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= form.label :"MiniBook Name" %></div>
  <div id = "book_field_input"><%= form.text_field :minibook_name, :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
 <%= form.number_field :user_id, id: :mini_book_user_id, value: current_user.id, readonly: true, type: :hidden %>
</div>

<div class="field", id = "book_entry_field">
  <%= form.hidden_field :id, :value => params[:id]%>
</div>

</div>
<div id = "entry_submit_button_cont">
  <button class="btn", id= "entry_submit_button"><%= link_to "Back", mini_books_path %></button>
  <%= form.submit :"Create Minibook", class: 'btn', id: "entry_submit_button" %>
</div>
<% end %>

app/views/mini_books/edit.html.erb
<%= form_with scope: :mini_book, url: mini_book_path, model: @mini_book, method: :put, :local => true do |form| %>

  <% if @mini_book.errors.any? %>
    <ul>
      <% @mini_book.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div id = "book__entry__form">
  <h1 id ="mainbook__entry">Create Minibook</h1>
<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= form.label :"MiniBook Name" %></div>
  <div id = "book_field_input"><%= form.text_field :minibook_name, :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
 <%= form.number_field :user_id, id: :mini_book_user_id, value: current_user.id, readonly: true, type: :hidden %>
</div>

<div class="field", id = "book_entry_field">
  <%= form.hidden_field :id, :value => params[:id]%>
</div>

</div>
<div id = "entry_submit_button_cont">
  <button class="btn", id= "entry_submit_button"><%= link_to "Back", mini_books_path %></button>
  <%= form.submit :"Update Minibook", class: 'btn', id: "entry_submit_button" %>
</div>
<% end %>

app/views/mini_books/export_pdf.html.erb
<h3> PDF Generation date: <%= Time.zone.now%> </h3>

<div class = "books-table-header"> ALL MINIBOOKS </div>
<div class = "books-table-container">
<div class="table-responsive-lg">
  <div class="product_list_container">
  <table class = "table">
    <tr scope="column">
      <td>MiniBook ID</td>
      <td>Minibook Name</td>
      <td>Minibook Price</td>
    </tr>
    <% @mini_books.each do |minibook| %>
    <% if minibook.user == current_user %>
      <tr scope="column">  
        <td><%= minibook.id %></td>
        <td><%= minibook.minibook_name %></td>
    </tr>
    <% end %>
    <% end %>
  </table>
  </div>
</div>
</div>

app/views/mini_books/index.html.erb
<div class="container-fluid px-6">
  <div class="row">
    <div>
      <div class="card" id= "card_mainbook_header__minibook">
        <div class="card-body" , id="mainbook__header">MINIBOOKS</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
        </div>
      </div>
      <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active", id="buttons__minibooks">
            <button type="button" class="btn btn-outline-light", id="book__buttons_minib">
                <%= link_to "Back", user_dashboard_path %>
              </button>
              <button type="button" class="btn btn-outline-light", id="book__buttons_minib">
                <%= link_to "Create Minibook", new_mini_book_path %>
              </button>
               </button>
              <button type="button" class="btn btn-outline-light", id="book__buttons_minib">
                <%= link_to "Export", minibook_export_path(format: :pdf) %>
              </button>
            </li>
          </ol>
    </div>
  </div>
<%= render 'all_minibooks' %>
</div>

app/views/mini_books/new.html.erb
<%= render 'minibook_form' %>

app/views/mini_books/show.html.erb
<h1> SHOW minibook data <h1>

  <button type="button" class="btn btn-outline-light"><%= link_to "Back", mini_books_path %></button>
  <button type="button" class="btn btn-outline-light"><%= link_to "Create New Mini Book", new_mini_book_path %></button>
  <%#= link_to "Create Entry", new_minibook_entry_path %>