config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home_page'
  
  # users
  get '/user_dashboard' => 'users#user_dashboard', as: 'user_dashboard'

  # MainBook
  get '/mainbook' => 'main_books#index'
  get '/mainbook_entries' => 'main_books#mainbook_entries'
  get '/mainbook_entry' => 'main_books#new', as: 'mainbook_new'
  post '/mainbook_entry' => 'main_books#create', as: 'mainbook_entry'
  get '/mainbook/:id/edit' => 'main_books#edit', as: 'edit_mainbook'
  put '/mainbook/:id/edit' => 'main_books#update', as: 'update_mainbook'
  post '/mainbook/:id/delete' => 'main_books#destroy_entry', as: 'delete_entry'

  # export to pdf
  get '/mainbook_export' => 'main_books#export_pdf', as: 'mainbook_export'
  get '/minibook_export' => 'mini_books#export_pdf', as: 'minibook_export'
  get 'mini_books/:mini_book_id/minibook_entries_export' => 'minibook_entries#export_pdf', as: 'minibook_entries_export'

  resources :mini_books do
    resources :minibook_entries
  end

  # Admin
  get 'admins/home' => 'admin_pages#index'
  get 'admins/all_users' => 'admin_pages#all_users'
  get 'admins/paid_users' => 'admin_pages#paid_users'
  get 'admins/free_users' => 'admin_pages#free_users'

  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }, only: [:sessions]

  # user
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations" }, only: [:sessions, :registrations, :confirmations]
 
  
  # scope '/checkout' do
  #   post 'create', to: 'checkout#create', as: 'checkout_create'
  #   get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  #   get 'success', to: 'checkout#success', as: 'checkout_success'
  # end

  #resources :checkout, only: [:create]
  post "checkouts/create", to: "checkouts#create", as: "checkout_create"

  # Products
  get '/products' => 'abc_products#index'
  get '/product/:id/show' => 'abc_products#show', as: 'abc_product_show'
  # get '/product_new' => 'abc_products#new', as: 'abc_product_new'
  # post '/product_new' => 'abc_products#create', as: 'abc_product_create'
  # get '/product/:id/edit' => 'abc_products#edit', as: 'edit_abc_product'
  # put '/product/:id/edit' => 'abc_products#update', as: 'update_abc_product'
  # post '/product/:id/delete' => 'abc_products#destroy', as: 'delete_abc_product'

  get 'pricing', to: 'static_pages#pricing'
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]
end

app/models/minibook_entry.rb
class MinibookEntry < ApplicationRecord
  belongs_to :mini_book
  belongs_to :user

  validates :user_id, presence: true
  validates :date_minib_entry, presence: true
  validates :minibook_entry_description, presence: true
  validates :or_vat_reg_tin_minib, presence: true
end

app/controllers/minibook_entries_controller.rb
class MinibookEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_minibook
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @mini_book_id = params[:mini_book_id]
    @minibook_entries = MiniBook.find(params[:mini_book_id]).minibook_entries
  end

  def export_pdf
    @mini_book_id = params[:mini_book_id]
    @minibook_entries = MiniBook.find(params[:mini_book_id]).minibook_entries
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Minibook entry #{@mini_book.minibook_name} as of: #{Time.zone.today}", template: 'minibook_entries/export_pdf.html.erb'
      end
    end
  end

  def new
    @minibook_entry = @mini_book.minibook_entries.build
  end

  def create
    @minibook_entry = @mini_book.minibook_entries.build(minibook_entries_params)
    if @minibook_entry.save
      redirect_to mini_book_minibook_entries_path
    else
      render :new
    end
  end

  def edit
    @minibook_entry = MinibookEntry.find(params[:id])
  end

  def update
    @minibook_entry = MinibookEntry.find(params[:id])
    if @minibook_entry.update(minibook_entries_params)
      flash[:notice] = 'Sucessfully updated Minibook entry'
      redirect_to mini_book_minibook_entries_path(@minibook_entry.mini_book_id)
    else
      render :edit
    end
  end

  def destroy
    @minibook_entry = MinibookEntry.find(params[:id])
    if @minibook_entry.destroy
      flash[:notice] = 'Sucessfully deleted Minibook Entry'
      redirect_to mini_book_minibook_entries_path(@minibook_entry.mini_book_id)
    else
      render :mini_book_minibook_entries_path
    end
  end

  def correct_user
    @minibook_entry = current_user.minibook_entries.find_by(id: params[:id])
    redirect_to mini_book_minibook_entries_path, notice: 'Not Authorized to access this page' if @minibook_entry.nil?
  end

  private

  def correct_minibook
    @mini_book = MiniBook.find(params[:mini_book_id])
  end

  def minibook_entries_params
    params.require(:minibook_entry).permit(:mini_book_id, :date_minib_entry, :minibook_entry_description, :or_vat_reg_tin_minib, :debit_minib, :credit_minib, :minibook_balance, :user_id)
  end
end

app/helpers/minibook_entries_helper.rb
module MinibookEntriesHelper
end

app/views/minibook_entries/_all_minibook_entries.html.erb
<section class="p-3 my-container">
  <div class="books-table-container">
    <div class="container">
      <div class="card-body", id = "book__entry__table_mainbook_entries">
        <div class="table-responsive">
          <table class="table table-borderless text-white mb-0">
            <thead>
              <tr>
                <td class="label_book_header">Entry ID</td>
                <td class="label_book_header">Entry Date</td>
                <td class="label_book_header">Description</td>
                <td class="label_book_header">or-or_vat_reg_tin</td>
                <td class="label_book_header">DEBIT (+)</td>
                <td class="label_book_header">CREDIT (-)</td>
                <td class="label_book_header">Balance</td>
                <td class="label_book_header">Action</td>
              </tr>
            </thead>
            <tbody>
              <% running_total = 0 %> 
              <% @minibook_entries.each do |minibook_entry| %>
              <% if minibook_entry.user == current_user %>
              <tr scope="column">
                <td><%= minibook_entry.id %></td>
                <td><%= minibook_entry.date_minib_entry.strftime('%B %d, %Y') %></td>
                <td><%= minibook_entry.minibook_entry_description %></td>
                <td><%= minibook_entry.or_vat_reg_tin_minib %></td>
                <td><%= number_to_currency(minibook_entry.debit_minib, unit: ' ₱ ') %></td>
                <td><%= number_to_currency(minibook_entry.credit_minib, unit: ' ₱ ') %></td>
                <td><%= number_to_currency(calculate_balance(minibook_entry.debit_minib, minibook_entry.credit_minib), unit: ' ₱ ') %></td>
                <% running_total = calculate_total_balance(running_total, calculate_balance(minibook_entry.debit_minib, minibook_entry.credit_minib)) %>
                <td>
                  <button type="button" class="btn btn-outline-light", id="table__inside__buttons"><%= link_to "Edit", edit_mini_book_minibook_entry_path(minibook_entry.mini_book_id, minibook_entry.id) %></button>
                  <button type="button" class="btn btn-outline-light", id="table__inside__buttons"><%= link_to "Delete", mini_book_minibook_entry_path(minibook_entry.mini_book_id, minibook_entry.id), method: :delete, :data => { :confirm => "Are you sure?" } %></button>
                </td>
              </tr>
              <% end %> 
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/minibook_entries/_minibook_entry_form.html.erb
<%= form_with scope: :minibook_entry, url: mini_book_minibook_entries_path, model: [@minibook_entry.mini_book, @minibook_entry], :local => true do |f| %>
    <% if @minibook_entry.errors.any? %>
    <ul>
      <% @minibook_entry.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div id = "book__entry__form">
  <h1 id ="mainbook__entry">Create Minibook Entry</h1>
<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Date" %></div>
  <div id = "book_field_input"><%= f.date_field :date_minib_entry, :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Description"%></div>
  <div id = "book_field_input"><%= f.text_field :minibook_entry_description, autofocus: true, placeholder: "Description", :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"or-vat-reg-tin"%></div>
  <div id = "book_field_input"><%= f.text_field :or_vat_reg_tin_minib, placeholder: "OR VAT-REG-TIN" %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"DEBIT (+)"%></div>
  <div id = "book_field_input"><%= f.number_field :debit_minib, placeholder: "DEBIT (+)", step: :any, value: '00.0' %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"CREDIT (-)"%></div>
  <div id = "book_field_input"><%= f.number_field :credit_minib, placeholder: "CREDIT (-)", step: :any, value: '00.0' %></div>
</div>

 <div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.number_field :user_id, id: :minibook_entry_user_id, value: current_user.id, type: :hidden %></div>
</div>
</div>
<div id = "entry_submit_button_cont">
  <button class="btn", id= "entry_submit_button"><%= link_to "Back", mini_book_minibook_entries_path %></button>
  <%= f.submit :"Add Entry", class: 'btn', id: "entry_submit_button" %>
</div>
<% end %>

app/views/minibook_entries/edit.html.erb
<%= form_with scope: :minibook_entry, url: mini_book_minibook_entry_path, model: [@minibook_entry.mini_book, @minibook_entry], method: :put, :local => true do |f| %>
  <h1>Edit Minibook entry</h1>

  <% if @minibook_entry.errors.any? %>
    <ul>
      <% @minibook_entry.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div id = "book__entry__form">
  <h1 id ="mainbook__entry">Create Minibook Entry</h1>
<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Date" %></div>
  <div id = "book_field_input"><%= f.date_field :date_minib_entry, :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Description"%></div>
  <div id = "book_field_input"><%= f.text_field :minibook_entry_description, autofocus: true, placeholder: "Description", :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"or-vat-reg-tin"%></div>
  <div id = "book_field_input"><%= f.text_field :or_vat_reg_tin_minib, placeholder: "OR VAT-REG-TIN" %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"DEBIT (+)"%></div>
  <div id = "book_field_input"><%= f.number_field :debit_minib, placeholder: "DEBIT (+)", step: :any, value: '00.0' %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"CREDIT (-)"%></div>
  <div id = "book_field_input"><%= f.number_field :credit_minib, placeholder: "CREDIT (-)", step: :any, value: '00.0' %></div>
</div>

 <div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.number_field :user_id, id: :minibook_entry_user_id, value: current_user.id, type: :hidden %></div>
</div>
</div>
<div id = "entry_submit_button_cont">
  <button class="btn", id= "entry_submit_button"><%= link_to "Back", mini_book_minibook_entries_path %></button>
  <%= f.submit :"Update", class: 'btn', id: "entry_submit_button" %>
</div>
<% end %>

app/views/minibook_entries/export_pdf.html.erb
<h3> PDF Generation date: <%= Time.zone.now%> </h3>

<div class = "books-table-header"> ALL MINIBOOK Entries</div>
<div class = "books-table-container">
  <div class="table-responsive-lg">
  <table class = "table">
  <tr scope="column">
    <td class = "label">Entry ID</td>
    <td class = "label">Minibook_ID</td>
    <td class = "label">Entry Date</td>
    <td class = "label">Description</td>
    <td class = "label">or-or_vat_reg_tin</td>
    <td class = "label">DEBIT (+)</td>
    <td class = "label">CREDIT (-)</td>
    <td class = "label">Balance</td>
  </tr>
  <% running_total = 0 %>
  <% @minibook_entries.each do |minibook_entry| %>
  <% if minibook_entry.user == current_user %>
  <tr scope="column">  
    <td><%= minibook_entry.id %></td>
    <td><%= minibook_entry.mini_book_id %></td>
    <td><%= minibook_entry.date_minib_entry.strftime('%B %d, %Y') %></td>
    <td><%= minibook_entry.minibook_entry_description %></td>
    <td><%= minibook_entry.or_vat_reg_tin_minib %></td>
    <td><%= number_to_currency(minibook_entry.debit_minib, unit: ' PHP ') %></td>
    <td><%= number_to_currency(minibook_entry.credit_minib, unit: ' PHP ') %></td>
    <td><%= number_to_currency(calculate_balance(minibook_entry.debit_minib, minibook_entry.credit_minib), unit: ' PHP ') %></td>
    <td><% running_total = calculate_total_balance(running_total, calculate_balance(minibook_entry.debit_minib, minibook_entry.credit_minib)) %></td>
  </tr>
  <% end %>
  <% end %>
  </table>
  </div>
</div>

<div>
<h2> TOTAL BALANCE: <%= number_to_currency(running_total, unit: ' PHP ') %></h2>
</div>

app/views/minibook_entries/index.html.erb
<div class="container-fluid px-6">
  <div class="row">
    <% running_total = 0 %> 
    <% running_total_credit = 0 %> 
    <% running_total_debit = 0 %> 
    <% @minibook_entries.each do |minibook_entry| %> 
    <% if minibook_entry.user == current_user %> 
      <% running_total = calculate_total_balance(running_total, calculate_balance(minibook_entry.debit_minib, minibook_entry.credit_minib)) %> 
    <% end %>
    <% end %>
    <div>
      <div class="card" id= "card_mainbook_header">
        <div class="card-body" , id="mainbook__header">MINIBOOK ENTRIES</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <h5><%= "Total balance: "%><%= number_to_currency(running_total, unit: '₱ ') %></h5>
        </div>
      </div>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active", id="buttons__books">
              <button type="button" class="btn btn-outline-light", id="book__buttons"><%= link_to "Back", mini_book_minibook_entries_path %></button>
              <button type="button" class="btn btn-outline-light", id="book__buttons"><%= link_to "Add Entry", new_mini_book_minibook_entry_path(@mini_book_id) %></button>
              <button type="button" class="btn btn-outline-light", id="book__buttons"><%= link_to "Export", minibook_entries_export_path(@mini_book_id, format: :pdf) %></button>
            </li>
        </ol>
    </div>
  </div>
<%= render 'all_minibook_entries'%>
</div>

app/views/minibook_entries/new.html.erb
<%= render 'minibook_entry_form' %>