config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home_page'
  
  # users
  get '/user_dashboard' => 'users#user_dashboard', as: 'user_dashboard'

  # MainBook
  get '/mainbook' => 'main_books#index'
  get '/mainbook_entries' => 'main_books#mainbook_entries'
  get '/mainbook_entry' => 'main_books#new', as: 'mainbook_new'
  post '/mainbook_entry' => 'main_books#create', as: 'mainbook_entry'
  get '/mainbook/:id/edit' => 'main_books#edit', as: 'edit_mainbook'
  put '/mainbook/:id/edit' => 'main_books#update', as: 'update_mainbook'
  post '/mainbook/:id/delete' => 'main_books#destroy_entry', as: 'delete_entry'

  # export to pdf
  get '/mainbook_export' => 'main_books#export_pdf', as: 'mainbook_export'
  get '/minibook_export' => 'mini_books#export_pdf', as: 'minibook_export'
  get 'mini_books/:mini_book_id/minibook_entries_export' => 'minibook_entries#export_pdf', as: 'minibook_entries_export'

  resources :mini_books do
    resources :minibook_entries
  end

  # Admin
  get 'admins/home' => 'admin_pages#index'
  get 'admins/all_users' => 'admin_pages#all_users'
  get 'admins/paid_users' => 'admin_pages#paid_users'
  get 'admins/free_users' => 'admin_pages#free_users'

  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }, only: [:sessions]

  # user
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations" }, only: [:sessions, :registrations, :confirmations]
 
  
  # scope '/checkout' do
  #   post 'create', to: 'checkout#create', as: 'checkout_create'
  #   get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  #   get 'success', to: 'checkout#success', as: 'checkout_success'
  # end

  #resources :checkout, only: [:create]
  post "checkouts/create", to: "checkouts#create", as: "checkout_create"

  # Products
  get '/products' => 'abc_products#index'
  get '/product/:id/show' => 'abc_products#show', as: 'abc_product_show'
  # get '/product_new' => 'abc_products#new', as: 'abc_product_new'
  # post '/product_new' => 'abc_products#create', as: 'abc_product_create'
  # get '/product/:id/edit' => 'abc_products#edit', as: 'edit_abc_product'
  # put '/product/:id/edit' => 'abc_products#update', as: 'update_abc_product'
  # post '/product/:id/delete' => 'abc_products#destroy', as: 'delete_abc_product'

  get 'pricing', to: 'static_pages#pricing'
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]
end

app/models/main_book.rb
class MainBook < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :date_mainb, presence: true
  validates :mainbook_description, presence: true
  validates :or_vat_reg_tin_mainb, presence: true
end

app/controllers/main_books_controller.rb
class MainBooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: %i[edit update destroy_entry]

  def index
    @main_books = MainBook.all
  end

  def export_pdf
    @main_books = MainBook.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Mainbook Entries as of: #{Time.zone.today}", template: 'main_books/export_pdf.html.erb'
      end
    end
  end

  def mainbook_entries
    @main_books = MainBook.all
  end

  def new
    @main_book = current_user.main_books.build
  end

  def create
    @main_book = current_user.main_books.build(main_book_params)
    if @main_book.save
      redirect_to mainbook_entries_path
    else
      render :new
    end
  end

  def edit
    @main_book = MainBook.find(params[:id])
  end

  def update
    @main_book = MainBook.find(params[:id])
    if @main_book.update(main_book_params)
      flash[:notice] = 'Sucessfully updated Mainbook entry'
      redirect_to mainbook_entries_path
    else
      render :edit
    end
  end

  def destroy_entry
    @main_book = MainBook.find(params[:id])
    if @main_book.destroy
      flash[:notice] = 'Sucessfully deleted Mainbook entry'
      redirect_to mainbook_entries_path
    else
      render :mainbook_entries_path
    end
  end

  def correct_user
    @main_book = current_user.main_books.find_by(id: params[:id])
    redirect_to mainbook_entries_path, notice: 'Not Authorized to access this page' if @main_book.nil?
  end

  private

  def main_book_params
    params.require(:main_book).permit(:user_id, :date_mainb, :mainbook_description, :or_vat_reg_tin_mainb, :debit_mainb, :credit_mainb, :balance_mainb)
  end
end

app/helpers/main_books_helper.rb
module MainBooksHelper
end

app/views/main_books/_all_mainbook_entries.html.erb
<section class="p-3 my-container">
  <div class="books-table-container">
    <div class="container">
      <div class="card-body", id = "book__entry__table">
        <div class="table-responsive">
          <table class="table table-borderless text-white mb-0">
            <thead>
              <tr>
                <td class="label_book_header">Entry ID</td>
                <td class="label_book_header">Date</td>
                <td class="label_book_header">Description</td>
                <td class="label_book_header">or-or_vat_reg_tin</td>
                <td class="label_book_header">DEBIT (+)</td>
                <td class="label_book_header">CREDIT (-)</td>
                <td class="label_book_header">Balance</td>
                <td class="label_book_header">Action</td>
              </tr>
            </thead>
            <tbody>
              <% running_total = 0 %> <% @main_books.each do |mainbook| %> <% if
              mainbook.user == current_user %>
              <tr scope="column">
                <td class="label_book_content"><%= mainbook.id %></td>
                <td class="label_book_content"><%= mainbook.date_mainb.strftime('%B %d, %Y') %></td>
                <td class="label_book_content"><%= mainbook.mainbook_description %></td>
                <td class="label_book_content"><%= mainbook.or_vat_reg_tin_mainb %></td>
                <td class="label_book_content">
                  <%= number_to_currency(mainbook.debit_mainb, unit: ' ₱ ') %>
                </td>
                <td class="label_book_content">
                  <%= number_to_currency(mainbook.credit_mainb, unit: ' ₱ ')
                  %>
                </td>
                <td class="label_book_content">
                  <%= number_to_currency(calculate_balance(mainbook.debit_mainb,
                  mainbook.credit_mainb), unit: ' ₱ ') %>
                </td>
                  <% running_total = calculate_total_balance(running_total,
                  calculate_balance(mainbook.debit_mainb,
                  mainbook.credit_mainb)) %>
                <td>
                  <button type="button" class="btn btn-outline-light", id="table__inside__buttons">
                    <%= link_to "Edit", edit_mainbook_path(mainbook.id) %>
                  </button>
                  <button type="button" class="btn btn-outline-light", id="table__inside__buttons">
                    <%= link_to "Delete", delete_entry_path(mainbook.id),
                    method: :destroy, :data => { :confirm => "Are you sure?" }
                    %>
                  </button>
                </td>
              </tr>
              <% end %> <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/main_books/_mainbook_form.html.erb
<%= form_with scope: :main_book, url: mainbook_entry_path, model: @main_book, :local => true do |f| %>

  <% if @main_book.errors.any? %>
    <ul>
      <% @main_book.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div id = "book__entry__form">
  <h1 id ="mainbook__entry">Create Mainbook Entry</h1>
<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Entry Date" %></div>
  <div id = "book_field_input"><%= f.date_field :date_mainb, :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Description"%></div>
  <div id = "book_field_input"><%= f.text_field :mainbook_description, autofocus: true, placeholder: "Description", :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"or-vat-reg-tin"%></div>
  <div id = "book_field_input"><%= f.text_field :or_vat_reg_tin_mainb, placeholder: "OR VAT-REG-TIN" %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"DEBIT (+)"%></div>
  <div id = "book_field_input"><%= f.number_field :debit_mainb, placeholder: "DEBIT (+)", step: :any, value: '00.0' %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"CREDIT (-)"%></div>
  <div id = "book_field_input"><%= f.number_field :credit_mainb, placeholder: "CREDIT (-)", step: :any, value: '00.0' %></div>
</div>

 <div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.number_field :user_id, id: :main_book_user_id, value: current_user.id, readonly: true, type: :hidden %></div>
</div>
</div>
<div id = "entry_submit_button_cont">
  <button class="btn", id= "entry_submit_button"><%= link_to "Back", mainbook_path%></button>
  <%= f.submit :"Add Entry", class: 'btn', id: "entry_submit_button" %>
</div>
<% end %>

app/views/main_books/edit.html.erb
<%= form_with scope: :main_book, url: update_mainbook_path, model: @main_book, method: :put, :local => true do |f| %>

  <% if @main_book.errors.any? %>
    <ul>
      <% @main_book.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<div id = "book__entry__form">
  <h1 id ="mainbook__entry">Create Mainbook Entry</h1>
<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Entry Date" %></div>
  <div id = "book_field_input"><%= f.date_field :date_mainb, :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"Description"%></div>
  <div id = "book_field_input"><%= f.text_field :mainbook_description, autofocus: true, placeholder: "Description", :required => true %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"or-vat-reg-tin"%></div>
  <div id = "book_field_input"><%= f.text_field :or_vat_reg_tin_mainb, placeholder: "OR VAT-REG-TIN" %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"DEBIT (+)"%></div>
  <div id = "book_field_input"><%= f.number_field :debit_mainb, placeholder: "DEBIT (+)", step: :any, value: '00.0' %></div>
</div>

<div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.label :"CREDIT (-)"%></div>
  <div id = "book_field_input"><%= f.number_field :credit_mainb, placeholder: "CREDIT (-)", step: :any, value: '00.0' %></div>
</div>

 <div class="field", id = "book_entry_field">
  <div id = "book_field_label"><%= f.number_field :user_id, id: :main_book_user_id, value: current_user.id, readonly: true, type: :hidden %></div>
</div>
</div>

<div id = "entry_submit_button_cont">
  <button class="btn", id= "entry_submit_button"><%= link_to "Back", mainbook_entries_path %></button>
  <%= f.submit :"Update", class: 'btn', id: "entry_submit_button" %>
</div>

<% end %>

app/views/main_books/export_pdf.html.erb
<h3> PDF Generation date: <%= Time.zone.now%> </h3>

<%= current_user.present? ? "" : "" %>
<h4 id = "user_welcome">Name: <%= current_user.full_name %></h4>

<div class="container-fluid px-6">
  <div class="row">
  <% running_total=0 %> <% running_total_credit=0 %> <%
      running_total_debit=0 %> <% @main_books.each do |mainbook| %> <% if
      mainbook.user==current_user %> <%
      running_total=calculate_total_balance(running_total,
      calculate_balance(mainbook.debit_mainb, mainbook.credit_mainb)) %> <%
      running_total_debit=calculate_total_debit(running_total_debit,
      mainbook.debit_mainb) %> <%
      running_total_credit=calculate_total_credit(running_total_credit,
      mainbook.credit_mainb) %> <% end %> <% end %>
    <div>
      <div class="card" id= "card_mainbook_header">
        <div class="card-body" , id="mainbook__header">MAINBOOK ENTRIES</div>
        <div
          class="card-footer d-flex align-items-center justify-content-between"
        >
          <h5><%= "Total balance: "%><%= number_to_currency(running_total, unit: '₱ ') %></h5>
          <h5><%= "Total Debit (+): "%><%= number_to_currency(running_total_debit, unit: ' PHP ' ) %></h5>
          <h5><%= "Total Credit(-): "%><%= number_to_currency(running_total_credit, unit: ' PHP ' ) %></h5>
        </div>
      </div>
    </div>
  </div>

<section class="p-3 my-container">
  <div class="books-table-container">
    <div class="container">
      <div class="card-body", id = "book__entry__table">
        <div class="table-responsive">
          <table class="table table-borderless text-white mb-0">
            <thead>
              <tr>
                <td class="label_book_header">Entry ID</td>
                <td class="label_book_header">Date</td>
                <td class="label_book_header">Description</td>
                <td class="label_book_header">or-or_vat_reg_tin</td>
                <td class="label_book_header">DEBIT (+)</td>
                <td class="label_book_header">CREDIT (-)</td>
                <td class="label_book_header">Balance</td>
              </tr>
            </thead>
            <tbody>
              <% running_total = 0 %> <% @main_books.each do |mainbook| %> <% if
              mainbook.user == current_user %>
              <tr scope="column">
                <td class="label_book_content"><%= mainbook.id %></td>
                <td class="label_book_content"><%= mainbook.date_mainb.strftime('%B %d, %Y') %></td>
                <td class="label_book_content"><%= mainbook.mainbook_description %></td>
                <td class="label_book_content"><%= mainbook.or_vat_reg_tin_mainb %></td>
                <td class="label_book_content">
                  <%= number_to_currency(mainbook.debit_mainb, unit: ' PHP ') %>
                </td>
                <td class="label_book_content">
                  <%= number_to_currency(mainbook.credit_mainb, unit: ' PHP ')
                  %>
                </td>
                <td class="label_book_content">
                  <%= number_to_currency(calculate_balance(mainbook.debit_mainb,
                  mainbook.credit_mainb), unit: ' PHP ') %>
                </td>
              </tr>
              <% end %> <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

</div>

app/views/main_books/index.html.erb
<div class="container-fluid px-6">
  <div class="row">
    <% running_total = 0 %> <% running_total_credit = 0 %> <%
    running_total_debit = 0 %> <% @main_books.each do |mainbook| %> <% if
    mainbook.user == current_user %> <% running_total =
    calculate_total_balance(running_total,
    calculate_balance(mainbook.debit_mainb, mainbook.credit_mainb)) %> <% end %>
    <% end %>
    <div>
      <div class="card" id= "card_mainbook_header">
        <div class="card-body" , id="mainbook__header">MAINBOOK ENTRIES</div>
        <div
          class="card-footer d-flex align-items-center justify-content-between"
        >
          <h5><%= "Total balance: "%><%= number_to_currency(running_total, unit: '₱ ') %></h5>
        </div>
      </div>
      <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active", id="buttons__books">
            <button type="button" class="btn btn-outline-light", id="book__buttons">
                <%= link_to "Back", user_dashboard_path %>
              </button>
              <button type="button" class="btn btn-outline-light", id="book__buttons">
                <%= link_to "Create Entry", mainbook_new_path %>
              </button>
               </button>
              <button type="button" class="btn btn-outline-light", id="book__buttons">
                <%= link_to "Export to PDF", mainbook_export_path(format: :pdf) %>
              </button>
            </li>
          </ol>
    </div>
  </div>

  <%= render 'all_mainbook_entries'%>
</div>

app/views/main_books/mainbook_entries.html.erb
<div class="container-fluid px-6">
  <div class="row">
    <% running_total = 0 %> <% running_total_credit = 0 %> <%
    running_total_debit = 0 %> <% @main_books.each do |mainbook| %> <% if
    mainbook.user == current_user %> <% running_total =
    calculate_total_balance(running_total,
    calculate_balance(mainbook.debit_mainb, mainbook.credit_mainb)) %> <% end %>
    <% end %>
    <div>
      <div class="card" id= "card_mainbook_header">
        <div class="card-body" , id="mainbook__header">MAINBOOK ENTRIES</div>
        <div
          class="card-footer d-flex align-items-center justify-content-between"
        >
          <h5><%= "Total balance: "%><%= number_to_currency(running_total, unit: '₱ ') %></h5>
        </div>
      </div>
      <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active", id="buttons__books">
            <button type="button" class="btn btn-outline-light", id="book__buttons">
                <%= link_to "Back", user_dashboard_path %>
              </button>
              <button type="button" class="btn btn-outline-light", id="book__buttons">
                <%= link_to "Add Entry", mainbook_new_path %>
              </button>
              <button type="button" class="btn btn-outline-light", id="book__buttons">
                <%= link_to "Export", mainbook_export_path(format: :pdf) %>
              </button>
            </li>
          </ol>
    </div>
  </div>

  <%= render 'all_mainbook_entries'%>
</div>

app/views/main_books/new.html.erb
<%= render 'mainbook_form'%>